[window]
padding = { x = 5, y = 5 }
decorations = "None"
opacity = 0.8
blur = true
position = { x = 0, y = 0 }
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16
